<a href="https://colab.research.google.com/github/mhc999/ML-PY/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [2]:
# Numpy  = Numerical Python 
# Numpy is faster than lists/tuples 

from time import process_time # it will calculate the process time


In [7]:
# list 
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [ i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

# this code gives us the time taken for adding 5 to all values in the list

0.0011256039999993916


In [8]:
#numpy 

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 

end_time = process_time()

print(end_time - start_time)

# numpy is faster than lists 

0.00017209099999959676


NUMPY ARRAYS


In [9]:
np_array = np.array([1,2,3,4,5])
print(np_array)

#In lists, the elements will be separated by a comma and in array, there is nothing like that

[1 2 3 4 5]


In [10]:
#creating a 1 dimensional array
a = np.array([1,2,3,4])
print(a)
a.shape # gives the dimension of the array

[1 2 3 4]


(4,)

In [12]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

#(no. of rows, no. of columns) 2 dimesnional 

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

#dtype= data type 

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


INITIAL PLACEHOLDERS IN NUMPY ARRAYS


In [14]:
#create a numpy array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#array full of a particular value
z = np.full((5,4), 5 )
print(z)

# z = np.full((rows,columns) , value)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
#create an identity matrix ( diagonal = 1 and the rest are zero) always square matrix
a = np.eye(4)
print(a)

# 4 is the rows= columns

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
#create a numpy array with random values 
b = np.random.random((3,4)) # all random values will be between 0 and 1 
print(b)

[[0.10245758 0.88614932 0.12005735 0.66704187]
 [0.56110762 0.46626688 0.79456449 0.10683209]
 [0.7945483  0.6440093  0.00873653 0.75996928]]


In [19]:
# create an array with random integers within a specific range
c = np.random.randint(10,100,(3,5))
# np.random.randint(range,(rows,columns))
print(c)


[[99 24 92 96 91]
 [44 88 38 81 28]
 [34 31 21 89 58]]


In [20]:
# array of evenly spaced values
d = np.linspace(10,30,5)
# np.linearlyspaced (start_range, end_Range, no.of values you want in that range)
print(d)

[10. 15. 20. 25. 30.]


In [22]:
#array of evenly spaced values specifying the step 
e = np.arange(10,30,5)
# np.arange(start_range,end_range, gap between the two numbers)
print(e)

[10 15 20 25]


In [24]:
#convert list to numpy array
list_1 = [10,20,30,20,50]

np_array = np.array(list_1)
print(np_array)
type(np_array)

[10 20 30 20 50]


numpy.ndarray

ANALYZING A NUMPY ARRAY


In [25]:
c = np.random.randint(10,90,(5,5))
print(c)

[[28 74 19 86 55]
 [25 76 19 62 62]
 [51 34 73 88 28]
 [26 22 87 41 26]
 [74 77 38 20 19]]


In [26]:
# find array dimension
print(c.shape)

(5, 5)


In [27]:
# np. of dimensions
print(c.ndim)
# rows and columns = 2

2


In [28]:
# no. of elements in an array
print(c.size)

25


In [29]:
#checking data type of values in the array
print(c.dtype)

int64


MATHEMATICAL OPERATIONS ON NUMPY ARRAY

In [30]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)
# basically the two lists will be concatenated

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 3 8]
 [3 2 2]
 [0 1 5]]
[[12 17 17]
 [15 10 12]
 [11 18 19]]


In [35]:
# ELEMENT WISE ADD/SUB/MULT/DIV WILL TAKE PLACE 
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[20 20 25]
 [18 12 14]
 [11 19 24]]
[[ -4 -14  -9]
 [-12  -8 -10]
 [-11 -17 -14]]
[[ 96  51 136]
 [ 45  20  24]
 [  0  18  95]]
[[0.66666667 0.17647059 0.47058824]
 [0.2        0.2        0.16666667]
 [0.         0.05555556 0.26315789]]


In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 0 6]
 [8 4 6]
 [9 7 6]]
[[15 14 12]
 [13 13 17]
 [13 13 12]]


In [37]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 14 18]
 [21 17 23]
 [22 20 18]]
[[ -7 -14  -6]
 [ -5  -9 -11]
 [ -4  -6  -6]]
[[120   0  72]
 [104  52 102]
 [117  91  72]]
[[0.53333333 0.         0.5       ]
 [0.61538462 0.30769231 0.35294118]
 [0.69230769 0.53846154 0.5       ]]


ARRAY MANIPULATION


In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 1 6]
 [2 3 4]]
(2, 3)


In [40]:
# find transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)
#or
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 2]
 [1 3]
 [6 4]]
(3, 2)
[[9 2]
 [1 3]
 [6 4]]
(3, 2)


In [41]:
#reshaping an array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[9 0 6]
 [0 9 8]]
(2, 3)


In [42]:
b = a.reshape(3,2)
#a.reshape(new rows,new columns)
print(b)
print(b.shape)

[[9 0]
 [6 0]
 [9 8]]
(3, 2)
